name = input("Enter your name: ")
age = int(input("Enter your AGE: "))
height = float(input("Enter your height(m): "))
print(type(name))
print(type(age))
print(type(height))
print("You are", age, "years old", "Your height is ", height, name)
