a = int(input("Enter your number a: "))
b = int(input("Enter your number b: "))
print(a," + ",b," = ", a + b)
print(a," - ",b," = ", a - b)
print(a," × ",b," = ", a * b)
print(a," ÷ ",b," = ", a / b)
print(a," ^ ",b," = ", a ** b)
print(a," ÷ ",b,"的餘數 = ", a % b)
